### ISSUE TITLE
sphinx-click does not warn if documentation is requested for an invalid object type

### ISSUE THREAD

**Issue by pmatos** [click-contrib/sphinx-click#13]
I am having an issue with `allow_extra_args`.

I get the following error:
```
Exception occurred:
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/click/core.py", line 254, in __init__
    allow_extra_args = command.allow_extra_args
AttributeError: module 'scripts.cfd' has no attribute 'allow_extra_args'
```

The whole backtrace is:
```
# Sphinx version: 1.6.3
# Python version: 3.6.0 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:
#   updating environment:
#   
#   6 added, 0 changed, 0 removed
#   
#   reading sources... [ 16%] api
#   
#   reading sources... [ 33%] authors
#   
#   reading sources... [ 50%] cfd
#   
# Loaded extensions:
#   alabaster (0.7.10) from /home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.6.3) from /home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx/ext/autodoc.py
#   sphinx.ext.intersphinx (1.6.3) from /home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.todo (1.6.3) from /home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx/ext/todo.py
#   sphinx.ext.autosummary (1.6.3) from /home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.viewcode (1.6.3) from /home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.coverage (1.6.3) from /home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.doctest (1.6.3) from /home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.ifconfig (1.6.3) from /home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx/ext/ifconfig.py
#   sphinx.ext.imgmath (1.6.3) from /home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx/ext/imgmath.py
#   sphinx.ext.napoleon (1.6.3) from /home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx/ext/napoleon/__init__.py
#   sphinx_click.ext (unknown version) from /home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx_click/ext.py
Traceback (most recent call last):
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 331, in build_update
    'out of date' % len(to_build))
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 344, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 583, in update
    self._read_serial(docnames, self.app)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 602, in _read_serial
    self.read_doc(docname, app)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 723, in read_doc
    pub.publish()
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx/io.py", line 74, in read
    self.parse()
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/docutils/parsers/rst/__init__.py", line 185, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2980, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2318, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2330, in explicit_construct
    return method(self, expmatch)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2073, in directive
    directive_class, match, type_name, option_presets)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2122, in run_directive
    result = directive_instance.run()
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx_click/ext.py", line 285, in run
    return self._generate_nodes(prog_name, command, None, show_nested)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/sphinx_click/ext.py", line 219, in _generate_nodes
    ctx = click.Context(command, info_name=name, parent=parent)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/click/core.py", line 254, in __init__
    allow_extra_args = command.allow_extra_args
AttributeError: module 'scripts.cfd' has no attribute 'allow_extra_args'
```

My code uses context to set `allow_extra_args`, and looks like:
```
@click.group()
@click.pass_context
def cli(ctx):
    ctx.allow_extra_args = False
    ctx.obj = Cfd()
```

However, I have found that even if I comment the line touching `ctx.allow_extra_args` I still get the problem. Maybe this is incompatible with `click 6.7`?

**Comment by stephenfin** [comment]
Could you give me a minimal case to reproduce this?

**Comment by 1oglop1** [comment]
@stephenfin I got the error as well, please check this as a minimal case

https://github.com/1oglop1/sphinx-click-error

**Comment by stephenfin** [comment]
> @stephenfin I got the error as well, please check this as a minimal case
> 
> https://github.com/1oglop1/sphinx-click-error

Thanks for that. The error message in both cases is caused by pointing to a module instead of a parser object. for the aforementioned project, you want to apply the following change.

```diff
diff --git a/docs/source/cli.rst b/docs/source/cli.rst
index 32441c3..40207a7 100644
--- a/docs/source/cli.rst
+++ b/docs/source/cli.rst
@@ -2,5 +2,5 @@ CLI DOC
 =======
 
 
-.. click:: helloapp.cli:init
-   :prog: clihello
\ No newline at end of file
+.. click:: helloapp.cli:cli
+   :prog: clihello
```

We should probably have some checks to ensure the correct object type is being passed in though. I can add these.

**Comment by 1oglop1** [comment]
Great thanks @stephenfin, it seems that I misunderstood the concept of `parser` object. Even after reading the documentation again I'm still not sure what it is, but docs were created as expected!
